데미지미터기:
  사용: true
  지속시간:
    초: 2
  형태: "{color}{symbol}{damage}"
  색상:
    일반: "&7"
    물리: "&c"
    마법: "&9"
    고정: "&f"
    회복: "&a"
  심볼:
    화염: "♨"
    원거리: "↗"
    폭발: "※"
무게:
  최대무게: 100
  무게당이속감소: 0.4
  기본이속: 120
무기:
  맨손:
    리치: 2.5
    무게: 0
    공속: 2
    데미지:
      1:
        데미지: 10
        속성: "Physics"
  DIAMOND_SWORD:
    리치: 3
    무게: 15
    공속: 2
    데미지:
      1:
        데미지: 27
        속성: "Physics"
      2:
        데미지: 9
        속성: "Magic"