데미지미터기:
  사용: true
  지속시간:
    초: 2
  형태: "{color}{symbol}{damage}"
  색상:
    일반: "&7"
    물리: "&c"
    마법: "&9"
    고정: "&f"
    회복: "&a"
  심볼:
    화염: "♨"
    원거리: "↗"
    폭발: "※"
아이템로어:
  사용: true
  형태:
    전체:
      - "&f{defence}"
      - "&f{attackDamage}"
      - "&f{projectileDamage}"
      - "&f{attribute}"
    구분선:
      방어력: "&7방어력----------"
      공격력: "&7공격력----------"
      발사체: "&7발사체----------"
      속성: "&7속성---------"
    공격속도: "&f공격속도: &e{value}"
    공격거리: "&f공격거리: &e{value}"
    무게: "&f무게: &e{value}"
    데미지속성:
      전체: "{tags}{value}"
      태그:
        발사체: "발사체"
        폭발: "폭발"
        화염: "화염"
        구분: " "
        접두사: "&7["
        접미사: "] "
      데미지:
        일반: "&7일반 {value}"
        물리: "&c물리 {value}"
        마법: "&9마법 {value}"
        고정: "&f고정 {value}"
        구분: " "

무게:
  최대무게: 100
  무게당이속감소: 0.4
  기본이속: 120
무기:
  맨손:
    리치: 2
    무게: 0
    공속: 2
    데미지:
      1:
        데미지: 10
        속성: "Physics"
  DIAMOND_SWORD:
    리치: 3
    무게: 15
    공속: 2
    데미지:
      방어관통:
        1:
          관통률: 0.2
          속성: "Magic"
      1:
        데미지: 27
        속성: "Physics"
      2:
        데미지: 9
        속성: "Magic"
갑옷:
  DIAMOND_CHESTPLATE:
    무게: 24
    방어:
      1:
        방어: 40
        속성: "Normal"
      2:
        방어: 12
        속성: "Physics"