데미지미터기:
  지속시간:
    초: 2
  형태: "{color}{symbol}{damage}"
  색상:
    일반: "&7"
    물리: "&c"
    마법: "&9"
    고정: "&f"
    회복: "&a"
  심볼:
    화염: "♨"
    원거리: "↗"
    폭발: "※"
    낙하: "▥"
아이템로어:
  형태:
    전체:
      - "&f{defence}"
      - "&f{attackDamage}"
      - "&f{projectileDamage}"
      - "&f{attribute}"
    구분선:
      방어력: "&7방어력----------"
      공격력: "&7공격력----------"
      방어관통: "&7방어관통(%)"
      발사체: "&7발사체----------"
      회복: "&7회복----------"
      속성: "&7속성---------"
    회복:
      동시섭취개수: "&f동시섭취개수: &e{value}"
      허기: "&f허기: &e{value}"
      회복: "&f회복: &a{value}"
      초당회복: "&f초당회복: &a{value}"
      지속시간: "&f지속시간: &e{value}"
      쿨타임: "&f쿨타임: &e{value}"
    속성:
      공격속도: "&f공격속도: &e{value}"
      공격거리: "&f공격거리: &e{value}"
      무게: "&f무게: &e{value}"
    데미지속성:
      전체: "{tags}{value}"
      태그:
        발사체: "발사체"
        폭발: "폭발"
        화염: "화염"
        낙하: "낙하"
        구분: " "
        접두사: "&7["
        접미사: "] "
      데미지:
        일반: "&7일반 {value}"
        물리: "&c물리 {value}"
        마법: "&9마법 {value}"
        고정: "&f고정 {value}"
        구분: " "
무게:
  최대무게: 100
  무게당이속감소: 0.4
  기본이속: 120
무기:
  맨손:
    리치: 2.5
    무게: 0
    공속: 2
    데미지:
      1:
        데미지: 10
        속성: "Physics"
  WOODEN_HOE:
    공속: 1.6
    리치: 4
    무게: 5
    데미지:
      1:
        데미지: 15
        속성: "Normal"
  WOODEN_SWORD:
    공속: 1.5
    리치: 3.4
    무게: 5
    데미지:
      1:
        데미지: 18
        속성: "Normal"
  WOODEN_SHOVEL:
    공속: 1.8
    리치: 3
    무게: 5
    데미지:
      1:
        데미지: 16
        속성: "Normal"
  WOODEN_PICKAXE:
    공속: 4
    리치: 2.2
    무게: -5
    데미지:
      1:
        데미지: 10
        속성: "Normal"
      2:
        데미지: 6
        속성: "Const"
  WOODEN_AXE:
    공속: 1
    리치: 2
    무게: 15
    데미지:
      방어관통:
        1:
          관통률: 0.30
          속성: "Const"
      1:
        데미지: 45
        속성: "Normal"
  STONE_HOE:
    공속: 1.28
    리치: 4
    무게: 20
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Physics"
      1:
        데미지: 20
        속성: "Physics"
  STONE_SWORD:
    공속: 1.2
    리치: 3.4
    무게: 20
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Physics"
      1:
        데미지: 25
        속성: "Physics"
  STONE_SHOVEL:
    공속: 1.44
    리치: 3
    무게: 20
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Physics"
      1:
        데미지: 23
        속성: "Physics"
  STONE_PICKAXE:
    공속: 3.2
    리치: 2.2
    무게: 10
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Physics"
      1:
        데미지: 12
        속성: "Physics"
      2:
        데미지: 8
        속성: "Const"
  STONE_AXE:
    공속: 0.8
    리치: 2
    무게: 30
    데미지:
      방어관통:
        1:
          관통률: 0.30
          속성: "Const"
        2:
          관통률: 0.8
          속성: "Physics"
      1:
        데미지: 60
        속성: "Physics"
  IRON_HOE:
    공속: 1.6
    리치: 4
    무게: 15
    데미지:
      1:
        데미지: 20
        속성: "Physics"
  IRON_SWORD:
    공속: 1.5
    리치: 3.4
    무게: 15
    데미지:
      1:
        데미지: 25
        속성: "Physics"
  IRON_SHOVEL:
    공속: 1.8
    리치: 3
    무게: 15
    데미지:
      1:
        데미지: 23
        속성: "Physics"
  IRON_PICKAXE:
    공속: 4
    리치: 2.2
    무게: 5
    데미지:
      1:
        데미지: 12
        속성: "Physics"
      2:
        데미지: 8
        속성: "Const"
  IRON_AXE:
    공속: 1
    리치: 2
    무게: 25
    데미지:
      방어관통:
        1:
          관통률: 0.30
          속성: "Const"
      1:
        데미지: 60
        속성: "Physics"
  GOLDEN_HOE:
    공속: 1.6
    리치: 4
    무게: 15
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Magic"
      1:
        데미지: 8
        속성: "Physics"
      2:
        데미지: 10
        속성: "Magic"
  GOLDEN_SWORD:
    공속: 1.5
    리치: 3.4
    무게: 15
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Magic"
      1:
        데미지: 11.25
        속성: "Physics"
      2:
        데미지: 12.5
        속성: "Magic"
  GOLDEN_SHOVEL:
    공속: 1.8
    리치: 3
    무게: 15
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Magic"
      1:
        데미지: 10
        속성: "Physics"
      2:
        데미지: 11.5
        속성: "Magic"
  GOLDEN_PICKAXE:
    공속: 4
    리치: 2.2
    무게: 5
    데미지:
      방어관통:
        1:
          관통률: 0.8
          속성: "Magic"
      1:
        데미지: 5
        속성: "Physics"
      2:
        데미지: 6
        속성: "Magic"
      3:
        데미지: 8
        속성: "Const"
  GOLDEN_AXE:
    공속: 1
    리치: 2
    무게: 25
    데미지:
      방어관통:
        1:
          관통률: 0.30
          속성: "Const"
        2:
          관통률: 0.8
          속성: "Magic"
      1:
        데미지: 27
        속성: "Physics"
      2:
        데미지: 27
        속성: "Magic"
  DIAMOND_HOE:
    공속: 1.6
    리치: 4
    무게: 20
    데미지:
      1:
        데미지: 20
        속성: "Magic"
  DIAMOND_SWORD:
    공속: 1.5
    리치: 3.4
    무게: 20
    데미지:
      1:
        데미지: 25
        속성: "Magic"
  DIAMOND_SHOVEL:
    공속: 1.8
    리치: 3
    무게: 20
    데미지:
      1:
        데미지: 23
        속성: "Magic"
  DIAMOND_PICKAXE:
    공속: 4
    리치: 2.2
    무게: 10
    데미지:
      1:
        데미지: 12
        속성: "Magic"
      2:
        데미지: 8
        속성: "Const"
  DIAMOND_AXE:
    공속: 1
    리치: 2
    무게: 30
    데미지:
      방어관통:
        1:
          관통률: 0.30
          속성: "Const"
      1:
        데미지: 60
        속성: "Magic"
  NETHERITE_HOE:
    공속: 1.28
    리치: 4
    무게: 25
    데미지:
      방어관통:
        1:
          관통률: 0.50
          속성: "Normal"
      1:
        데미지: 20
        속성: "Physics"
      2:
        데미지: 4
        속성: "Const"
  NETHERITE_SWORD:
    공속: 1.2
    리치: 3.4
    무게: 25
    데미지:
      방어관통:
        1:
          관통률: 0.50
          속성: "Normal"
      1:
        데미지: 25
        속성: "Physics"
      2:
        데미지: 5
        속성: "Const"
  NETHERITE_SHOVEL:
    공속: 1.44
    리치: 3
    무게: 25
    데미지:
      방어관통:
        1:
          관통률: 0.50
          속성: "Normal"
      1:
        데미지: 23
        속성: "Physics"
      2:
        데미지: 4.6
        속성: "Const"
  NETHERITE_PICKAXE:
    공속: 3.2
    리치: 2.2
    무게: 15
    데미지:
      방어관통:
        1:
          관통률: 0.50
          속성: "Normal"
      1:
        데미지: 12
        속성: "Physics"
      2:
        데미지: 12
        속성: "Const"
  NETHERITE_AXE:
    공속: 0.8
    리치: 2
    무게: 35
    데미지:
      방어관통:
        1:
          관통률: 0.30
          속성: "Const"
        2:
          관통률: 0.50
          속성: "Normal"
      1:
        데미지: 60
        속성: "Physics"
      2:
        데미지: 12
        속성: "Const"
  TRIDENT:
    공속: 1.8
    리치: 3.5
    무게: 15
    데미지:
      방어관통:
        1:
          관통률: 0.5
          속성: "Physics"
        2:
          관통률: 0.5
          속성: "Magic"
      1:
        데미지: 5
        속성: "Physics"
      2:
        데미지: 5
        속성: "Magic"
      3:
        데미지: 5
        속성: "Const"
갑옷:
  LEATHER_HELMET:
    무게: 0
    방어:
      1:
        방어: 20
        속성: "Physics"
  LEATHER_CHESTPLATE:
    무게: 15
    방어:
      1:
        방어: 40
        속성: "Physics"
  LEATHER_LEGGINGS:
    무게: 5
    방어:
      1:
        방어: 25
        속성: "Physics"
  LEATHER_BOOTS:
    무게: 0
    방어:
      1:
        방어: 15
        속성: "Physics"
      2:
        방어: 50
        속성: "Normal"
        타입:
          - "Fall"
  CHAINMAIL_HELMET:
    무게: 10
    방어:
      1:
        방어: 20
        속성: "Normal"
      2:
        방어: -20
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: -20
        속성: "Normal"
        타입:
          - "Fire"
  CHAINMAIL_CHESTPLATE:
    무게: 25
    방어:
      1:
        방어: 40
        속성: "Normal"
      2:
        방어: -40
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: -40
        속성: "Normal"
        타입:
          - "Fire"
  CHAINMAIL_LEGGINGS:
    무게: 15
    방어:
      1:
        방어: 25
        속성: "Normal"
      2:
        방어: -25
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: -25
        속성: "Normal"
        타입:
          - "Fire"
  CHAINMAIL_BOOTS:
    무게: 10
    방어:
      1:
        방어: 15
        속성: "Normal"
      2:
        방어: -15
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: -15
        속성: "Normal"
        타입:
          - "Fire"
      4:
        방어: 50
        속성: "Normal"
        타입:
          - "Fall"
  IRON_HELMET:
    무게: 10
    방어:
      1:
        방어: 15
        속성: "Normal"
      2:
        방어: 5
        속성: "Physics"
  IRON_CHESTPLATE:
    무게: 25
    방어:
      1:
        방어: 25
        속성: "Normal"
      2:
        방어: 15
        속성: "Physics"
  IRON_LEGGINGS:
    무게: 15
    방어:
      1:
        방어: 15
        속성: "Normal"
      2:
        방어: 10
        속성: "Physics"
  IRON_BOOTS:
    무게: 10
    방어:
      1:
        방어: 10
        속성: "Normal"
      2:
        방어: 5
        속성: "Physics"
      3:
        방어: 30
        속성: "Normal"
        타입:
          - "Fall"
  GOLDEN_HELMET:
    무게: 10
    방어:
      1:
        방어: 6
        속성: "Normal"
      2:
        방어: 7
        속성: "Physics"
      3:
        방어: 7
        속성: "Magic"
  GOLDEN_CHESTPLATE:
    무게: 25
    방어:
      1:
        방어: 10
        속성: "Normal"
      2:
        방어: 15
        속성: "Physics"
      3:
        방어: 15
        속성: "Magic"
  GOLDEN_LEGGINGS:
    무게: 15
    방어:
      1:
        방어: 5
        속성: "Normal"
      2:
        방어: 10
        속성: "Physics"
      3:
        방어: 10
        속성: "Magic"
  GOLDEN_BOOTS:
    무게: 10
    방어:
      1:
        방어: 6
        속성: "Normal"
      2:
        방어: 7
        속성: "Physics"
      3:
        방어: 7
        속성: "Magic"
      4:
        방어: 30
        속성: "Normal"
        타입:
          - "Fall"
  DIAMOND_HELMET:
    무게: 15
    방어:
      1:
        방어: 20
        속성: "Normal"
      2:
        방어: 10
        속성: "Magic"
  DIAMOND_CHESTPLATE:
    무게: 30
    방어:
      1:
        방어: 32
        속성: "Normal"
      2:
        방어: 16
        속성: "Magic"
  DIAMOND_LEGGINGS:
    무게: 20
    방어:
      1:
        방어: 20
        속성: "Normal"
      2:
        방어: 10
        속성: "Magic"
  DIAMOND_BOOTS:
    무게: 15
    방어:
      1:
        방어: 12
        속성: "Normal"
      2:
        방어: 6
        속성: "Magic"
      3:
        방어: 30
        속성: "Normal"
        타입:
          - "Fall"
  NETHERITE_HELMET:
    무게: 20
    방어:
      1:
        방어: 24
        속성: "Normal"
      2:
        방어: 20
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: 20
        속성: "Normal"
        타입:
          - "Fire"
  NETHERITE_CHESTPLATE:
    무게: 35
    방어:
      1:
        방어: 48
        속성: "Normal"
      2:
        방어: 40
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: 40
        속성: "Normal"
        타입:
          - "Fire"
  NETHERITE_LEGGINGS:
    무게: 25
    방어:
      1:
        방어: 50
        속성: "Normal"
      2:
        방어: 25
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: 25
        속성: "Normal"
        타입:
          - "Fire"
  NETHERITE_BOOTS:
    무게: 20
    방어:
      1:
        방어: 18
        속성: "Normal"
      2:
        방어: 15
        속성: "Normal"
        타입:
          - "Projectile"
      3:
        방어: 15
        속성: "Normal"
        타입:
          - "Fire"
      4:
        방어: 30
        속성: "Normal"
        타입:
          - "Fall"
발사체:
  기본:
    데미지:
      1:
        데미지: 25
        속성: "Physics"
        타입:
          - "Projectile"
  BOW:
    데미지:
      1:
        데미지: 30
        속성: "Physics"
        타입:
          - "Projectile"
      2:
        데미지: 5
        속성: "Const"
        타입:
          - "Projectile"
  CROSSBOW:
    데미지:
      방어관통:
        1:
          관통률: 0.5
          속성: "Const"
      1:
        데미지: 30
        속성: "Physics"
        타입:
          - "Projectile"
      2:
        데미지: 5
        속성: "Const"
        타입:
          - "Projectile"
  TRIDENT:
    데미지:
      방어관통:
        1:
          관통률: 0.5
          속성: "Physics"
        2:
          관통률: 0.5
          속성: "Magic"
      1:
        데미지: 15
        속성: "Physics"
        타입:
          - "Projectile"
      2:
        데미지: 15
        속성: "Magic"
        타입:
          - "Projectile"
      3:
        데미지: 5
        속성: "Const"
        타입:
          - "Projectile"
음식:
  설정:
    회복틱: 10
  COOKED_BEEF:
    최대섭취개수: 1
    허기: 6
    회복: 20
    초당회복: 7.5
    회복시간:
      초: 30
    쿨타임:
      초: 80
    쿨공유:
      - "BEEF"
  BEEF:
    최대섭취개수: 1
    허기: 3
    회복: 15
    초당회복: 3
    회복시간:
      초: 30
    쿨타임:
      초: 80
    쿨공유:
      - "COOKED_BEEF"
  COOKED_PORKCHOP:
    최대섭취개수: 1
    허기: 5
    회복: 30
    초당회복: 5
    회복시간:
      초: 30
    쿨타임:
      초: 60
    쿨공유:
      - "PORKCHOP"
  PORKCHOP:
    최대섭취개수: 1
    허기: 3
    회복: 15
    초당회복: 2
    회복시간:
      초: 30
    쿨타임:
      초: 60
    쿨공유:
      - "COOKED_PORKCHOP"
  COOKED_CHICKEN:
    최대섭취개수: 1
    허기: 4
    회복: 15
    초당회복: 3
    회복시간:
      초: 20
    쿨타임:
      초: 30
    쿨공유:
      - "CHICKEN"
  CHICKEN:
    최대섭취개수: 1
    허기: 2
    회복: 5
    초당회복: 2
    회복시간:
      초: 20
    쿨타임:
      초: 30
    쿨공유:
      - "COOKED_CHICKEN"
  COOKED_MUTTON:
    최대섭취개수: 1
    허기: 4
    회복: 15
    초당회복: 5
    회복시간:
      초: 20
    쿨타임:
      초: 40
    쿨공유:
      - "MUTTON"
  MUTTON:
    최대섭취개수: 1
    허기: 2
    회복: 5
    초당회복: 2
    회복시간:
      초: 20
    쿨타임:
      초: 40
    쿨공유:
      - "COOKED_MUTTON"
  COOKED_RABBIT:
    최대섭취개수: 1
    허기: 3
    회복: 30
    초당회복: 2
    회복시간:
      초: 15
    쿨타임:
      초: 25
    쿨공유:
      - "RABBIT"
  RABBIT:
    최대섭취개수: 1
    허기: 1
    회복: 10
    초당회복: 1
    회복시간:
      초: 15
    쿨타임:
      초: 25
    쿨공유:
      - "COOKED_RABBIT"
  SWEET_BERRIES:
    최대섭취개수: 8
    허기: 0.3
    회복: 2.5
    초당회복: 0
    회복시간:
      초: 0
    쿨타임:
      초: 0
  GLOW_BERRIES:
    최대섭취개수: 8
    허기: 0.3
    회복: 0
    초당회복: 1
    회복시간:
      초: 3
    쿨타임:
      초: 0
몬스터:
  ZOMBIE:
    1:
      데미지: 20
      속성: "Physics"
  HUSK:
    1:
      데미지: 20
      속성: "Physics"
  ZOMBIE_VILLAGER:
    1:
      데미지: 20
      속성: "Physics"
  DROWNED:
    1:
      데미지: 20
      속성: "Physics"
  PANDA:
    1:
      데미지: 25
      속성: "Physics"
  SPIDER:
    1:
      데미지: 5
      속성: "Physics"
    2:
      데미지: 10
      속성: "Magic"
  CAVE_SPIDER:
    1:
      데미지: 5
      속성: "Physics"
    2:
      데미지: 10
      속성: "Magic"
  SLIME:
    1:
      데미지: 30
      속성: "Magic"
  MAGMA_CUBE:
    1:
      데미지: 30
      속성: "Magic"
      타입:
        - "Fire"
  GHAST:
    1:
      데미지: 70
      속성: "Magic"
      타입:
        - "Explosion"
        - "Fire"
  ENDERMAN:
    1:
      데미지: 30
      속성: "Magic"
  BLAZE:
    1:
      데미지: 25
      속성: "Magic"
      타입:
        - "Fire"
  GUARDIAN:
    방어관통:
      1:
        관통률: 0.1
        속성: "Const"
    1:
      데미지: 40
      속성: "Magic"
  ELDER_GUARDIAN:
    방어관통:
      1:
        관통률: 0.3
        속성: "Const"
    1:
      데미지: 80
      속성: "Magic"
  WITHER_SKELETON:
    1:
      데미지: 20
      속성: "Physics"
  ZOGLIN:
    1:
      데미지: 15
      속성: "Physics"
  WARDEN:
    1:
      데미지: 40
      속성: "Const"
    2:
      데미지: 30
      속성: "Physics"
  EVOKER_FANGS:
    방어관통:
      1:
        관통률: 0.3
        속성: "Normal"
    1:
      데미지: 40
      속성: "Magic"
  RAVAGER:
    1:
      데미지: 100
      속성: "Physics"
  VEX:
    1:
      데미지: 20
      속성: "Magic"
  WITHER:
    방어관통:
      1:
        관통률: 0.3
        속성: "Const"
    1:
      데미지: 35
      속성: "Magic"
      타입:
        - "Projectile"
    2:
      데미지: 10
      속성: "Const"
      타입:
        - "Projectile"
  SHULKER:
    1:
      데미지: 10
      속성: "Magic"
      타입:
        - "Projectile"
  WOLF:
    1:
      데미지: 15
      속성: "Physics"
  POLAR_BEAR:
    1:
      데미지: 25
      속성: "Physics"
  PHANTOM:
    1:
      데미지: 20
      속성: "Physics"
  IRON_GOLEM:
    방어관통:
      1:
        관통률: 1
        속성: "Physics"
    1:
      데미지: 80
      속성: "Physics"
  ENDERMITE:
    1:
      데미지: 10
      속성: "Magic"
  ENDER_DRAGON:
    방어관통:
      1:
        관통률: 0.3
        속성: "Const"
    1:
      데미지: 20
      속성: "Physics"
    2:
      데미지: 40
      속성: "Magic"
    3:
      데미지: 20
      속성: "Const"
갑옷인첸트:
  protection: #보호
    기본:
      1:
        방어: 10
        속성: "Normal"
    레벨:
      1:
        방어: 10
        속성: "Normal"
  blast_protection: #폭발로부터 보호
    기본:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Explosion"
    레벨:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Explosion"
  fire_protection: #화염으로부터 보호
    기본:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Fire"
    레벨:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Fire"
  projectile_protection: #발사체로부터 보호
    기본:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Projectile"
    레벨:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Projectile"
  feather_falling: #가벼운 착지
    기본:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Fall"
    레벨:
      1:
        방어: 20
        속성: "Normal"
        타입:
          - "Fall"
무기인첸트:
  sharpness: #날카로움
    기본:
      1:
        데미지: 5
        속성: "Physics"
    레벨:
      1:
        데미지: 5
        속성: "Physics"
  bane_of_arthropods: #살충
    기본:
      1:
        데미지: 10
        속성: "Physics"
    레벨:
      1:
        데미지: 10
        속성: "Physics"
    대상:
      - "SPIDER"
      - "CAVE_SPIDER"
      - "SILVERFISH"
      - "ENDERMITE"
  smite: #강타
    기본:
      1:
        데미지: 10
        속성: "Physics"
    레벨:
      1:
        데미지: 10
        속성: "Physics"
    대상:
      - "SKELETON"
      - "ZOMBIE"
      - "WITHER"
      - "WITHER_SKELETON"
      - "ZOMBIFIED_PIGLIN"
      - "SKELETON_HORSE"
      - "PHANTOM"
      - "DROWNED"
      - "HUSK"
      - "STRAY"
      - "ZOMBIE_VILLAGER"
      - "ZOMBIE_HORSE"
  piercing: #찌르기
    기본:
      1:
        데미지: 2
        속성: "Physics"
      2:
        데미지: 2
        속성: "Magic"
      3:
        데미지: 1
        속성: "Const"
    레벨:
      1:
        데미지: 2
        속성: "Physics"
      2:
        데미지: 2
        속성: "Magic"
      3:
        데미지: 1
        속성: "Const"
발사체인첸트:
  power: #힘
    기본:
      1:
        데미지: 5
        속성: "Physics"
        타입:
          - "Projectile"
    레벨:
      데미지: 5
      속성: "Physics"
      타입:
        - "Projectile"
기타:
  데미지보정:
    플레이어: 1.0
    기타: 1.5
  불사의토템:
    최대섭취개수: 1
    허기: 10
    회복: 50
    초당회복: 20
    회복시간:
      초: 5
    쿨타임:
      분: 5
  방패:
    무게: 25
    방어:
      1:
        방어: 100
        속성: "Normal"
      2:
        방어: 100
        속성: "Normal"
        타입:
          - "Projectile"